### ISSUE TITLE
Set numberOfRecords('auto') if found any definitions with mode(permutation)

### ISSUE THREAD

**Issue by santiagoparradev** [Forceea/Forceea-data-factory#132]

**Comment by nmitrakis** [comment]
- An additional criterion should be: AND there is no `setNumberOfRecords(Number)`.
- This enhancement would make the `setNumberOfRecords('auto')` not required for most cases, which is good.
- We must determine in which scenarios the 'auto' will be required and test these scenarios.

**Comment by nmitrakis** [comment]
When we use permutations, there is a scenario where we don't want 'auto' calculating the number of generated records based on the permutations on field definitions. So, we should keep the capability that `setNumberOfRecords(number)` provides.

Under this consideration, we Forceea shouldn't set `setNumberOfRecords('auto')` when any permutations are found.
