### ISSUE TITLE
System.StringException: Invalid id when using FObject.setGlobalMocking(true)

### ISSUE THREAD

**Issue by ghost** [Forceea/Forceea-data-factory#137]
**Summary**

When attempting to cast an ID generated from ForceeaGenerator.getMockedIds, an exception is thrown:

System.StringException: Invalid id

However, this error is not seen if using fflib_IdGenerator.generate (we are using this library, too):

https://github.com/apex-enterprise-patterns/fflib-apex-mocks

It seems that the way their ID is generated doesn't cause a Salesforce exception.

**Repro**

In a test class, use FObject.setGlobalMocking(true)

..setup your data and insert records...

cast an ID somewhere after, such as like:

(Id) sObj.get(sObjectField)

**Workaround**

unknown

**Comment by nmitrakis** [comment]
Thank you for submitting this bug.
The ff-lib's method returns an Id data type, while Forceea returns a String, so it cannot be casted to an Id.
I'll try to fix it and include it in the upcoming release 2.2.0.
