### ISSUE TITLE
Vscode extension

### ISSUE THREAD

**Issue by AllanOricil** [Forceea/Forceea-data-factory#186]
### What is the current situation?

I really loved your lib and it is surely the closest thing I have ever seen to standardize data factories. Amazing job. 

I was thinking about creating a vscode extension to help me write the data definition language using some UI inputs. What do you think?

### Proposed solution

Vscode extension with an UI to generate code. 

### Benefits of new functionality

This view would show a sample of the data that would be generated and also be used to generate the code. This would speed up learning curve of the data definition language. And perhaps user adoption.

**Comment by nmitrakis** [comment]
Great idea! I had thought of a similar UI Salesforce app that would create all field definitions visually, generate the code and call Forceea to generate actual records, a solution targeting non-technical users. No time availability => plans are postponed.

But your suggestion would be very beneficial for Salesforce developers. Even I personally work with another IDE, I think that it could really give "life" to Dadela definitions in VSCode, making the process smoother and less tedious. But this is a project for a developer who knows how to write VSCode extensions (if I'm not wrong with TypeScript).

I would be glad to provide "design" guidance and advice to any developer(s) who would like to handle this challenge. If you can take it over, I will definitely help as a technical "Product Owner" :-)

Thank you for your support to Forceea!

**Comment by AllanOricil** [comment]
> Great idea! I had thought of a similar UI Salesforce app that would create all field definitions visually, generate the code and call Forceea to generate actual records, a solution targeting non-technical users. No time availability => plans are postponed.
> 
> But your suggestion would be very beneficial for Salesforce developers. Even I personally work with another IDE, I think that it could really give "life" to Dadela definitions in VSCode, making the process smoother and less tedious. But this is a project for a developer who knows how to write VSCode extensions (if I'm not wrong with TypeScript).
> 
> I would be glad to provide "design" guidance and advice to any developer(s) who would like to handle this challenge. If you can take it over, I will definitely help as a technical "Product Owner" :-)
> 
> Thank you for your support to Forceea!

Just sent some mockups and requirements and I will implement it for us :)

**Comment by nmitrakis** [comment]
As we discussed, we'll the VSCode extension offline. For the moment, I'm going to close this issue.
