### ISSUE TITLE
Wrong access modifier

### ISSUE THREAD

**Issue by Pooja-sfdc** [Forceea/Forceea-data-factory#200]
### Summary
At line 473 in FObject apex class, there is a  private property defined which is to define number of records that user wants to create. Since , this will be called from outside FObject class to defined number of records to create so should not be private.

 // the number of records to create
    private Integer records { get; set; }

### Reproduction

Created a test class by using below code, then I got error: 

DataFactory class code:
 public static FObject getDefAccounts() {
        FObject result = new FObject('Account');
        result.setDefinition('Name', 'static value(Company)');
        result.setDefinition('Name', 'serial type(number) from(1) step(1) scale(0)');
        result.setDefinition('Phone', 'random type(phone) format("(30) DDD dD-00-DD")');
        result.setDefinition('Industry', 'random type(picklist)');
        result.setDefinition('Site', 'random type(url)');
        result.setDefinition('Source_ID__c', 'static value(AL)');
        result.setDefinition('Source_ID__c', 'serial type(number) from(1) step(1) scale(0)');
        return result;
    }
    
    /*
    This new Template builds on the master Template getDefAccounts, 
    defining only the record type and the additional fields which are related to this 
    specific record type (NumberOfEmployees and AnnualRevenue). 
    All other defined fields from the master Template are used as they are, 
    so we don’t duplicate any field definitions. 

    Create a record type Template for each SObject’s record type, 
    with the name getDef<RecordTypeDescription><SObjectApiName>s, e.g. getDefServiceCases
    */
    // returns definitions for: Accounts with Customer record type
    public static FObject getDefCustomerAccounts() {
        FObject result = getDefAccounts();
        result.setDefinition('RecordTypeId', 'static value(Customer)');
        result.setDefinition('NumberOfEmployees', 'random type(number) from(10) to(100) scale(-1)');
        result.setDefinition('AnnualRevenue', 'random type(number) from(1000000) to(10000000) scale(3)');
        return result;
    }
    
    public static Map<String, FObject> getDefContactsAndAccounts() {
        Map<String, FObject> fobjectsByName = new Map<String, FObject>();
        String objName = '';
        objName = 'Account';
        FObject objAccount = getDefCustomerAccounts();
        fobjectsByName.put(objName, objAccount);
        objName = 'Contact';
        FObject objContact = new FObject(objName);
        objContact.setDefinition('FirstName', 'random type(firstname) group(name)');
        objContact.setDefinition('LastName', 'random type(lastname) group(name)');
        objContact.setDefinition('AccountId', 'random lookup(Account) source(forceea)');
        objContact.setDefinition('LeadSource', 'random type(picklist)');
        objContact.setDefinition('Title', 'random type(list) value(Developer, CFO, Account Manager, CEO, Logistics Manager)');
        objContact.setDefinition('Email', 'random type(email)');
        fobjectsByName.put(objName, objContact);
        
        return fobjectsByName;
    }
    
    public static void insertRecords(Map<String, FObject> fobjects) {
        for(FObject obj : fobjects.values()) {
            obj.insertRecords(true);
        }
    }

Test class code:

Map<String, FObject> fobjectsByName = DataFactoryDemo.getDefContactsAndAccounts();
        FObject objAccount = fobjectsByName.get('Account');
        FObject objContact = fobjectsByName.get('Contact');
        objAccount.records = 10;
        objContact.records = 100;
        objAccount.setDefinition('Description', 'random type(text) minlength(10) maxlength(40)');
        objAccount.setDefinition('Rating', 'random type(picklist) except(Hot)');
        objContact.setDefinition('Birthdate', 'random type(date) from(1960-1-1) to(2000-12-31)');
        DataFactoryDemo.insertRecords(fobjectsByName);

### Workaround

I just modified the access modifier of records property defined at 473 line in FObject class from Private to public .

**Comment by nmitrakis** [comment]
Hi @Pooja-sfdc, there is no need to modify the property.

The best practice for creating records with Forceea is totally different from what is included in your attached code.
Generally we create records by Templates (Forceea.Template class). There are plenty of examples in the Success Guide (see Data factory section).

If you insist on creating data without Forceea.Template,  you should use the following sample:
```
FObject obj = new FObject(Account.SObjectType, 10) \\ 10 is the number of records
    .setDefinition(.Account.Name, '......'.)
```
or
```
FObject obj = new FObject(Account.SObjectType)
    .setNumberOfRecords(10)
    .setDefinition(.....)
``

Again, please see the Success Guide for examples. For you reference I attach a sample Data Factory class:
```
public with sharing class DataFactory {

    public final static String ACCOUNTS = 'Accounts';
    public final static String MAJOR_ACCOUNTS = 'MajorAccounts';
    public final static String OPPORTUNITIES = 'Opportunities';
    public final static String B2B_OPPORTUNITIES = 'B2BOpportunities';

    public final static Integer DEFAULT_NUM_ACCOUNTS = 10;
    public final static Integer DEFAULT_NUM_OPPORTUNITIES = 40;

    public static Forceea.Template templateAccounts() {
        return new Forceea.Template()
            .add(ACCOUNTS, new FObject(Account.SObjectType)
                .setNumberOfRecords(DEFAULT_NUM_ACCOUNTS)
                .setDefinition(Account.Industry, 'random type(picklist) except(Electronics,Energy)')
                .setDefinition(Account.ShippingStreet, 'random type(street) group(shipping)')
                .setDefinition(Account.ShippingPostalCode, 'random type(postalCode) group(shipping)')
                .setDefinition(Account.ShippingCity, 'random type(city) group(shipping)')
                .setDefinition(Account.ShippingState, 'random type(state) group(shipping)')
                .setDefinition(Account.ShippingCountry, 'random type(country) group(shipping)')
            );
    }

    public static Forceea.Template templateMajorAccounts() {
        return new Forceea.Template()
            .add(MAJOR_ACCOUNTS, templateAccounts().getFObject(ACCOUNTS)
                .setVariable('recordType', 'MajorAccount')
                .setDefinition(Account.RecordTypeId, 'static value({@recordType})')
                .setDefinition(Account.Name, 'static value(Account-)')
                .setDefinition(Account.Name, 'serial type(number) from(1) step(1) scale(0)')
                .setDefinition(Account.AnnualRevenue, 'random type(number) from(1000000) to(100000000) scale(2)')
            );
    }

    public static Forceea.Template templateOpportunities() {
        return new Forceea.Template()
            .add(OPPORTUNITIES, new FObject(Opportunity.SObjectType)
                .setNumberOfRecords(DEFAULT_NUM_OPPORTUNITIES)
                .setVariable('today', Date.today())
                .setDefinition('$days', 'random type(number) from(-60) to(60) scale(0)')
                .setDefinition(Opportunity.CloseDate, 'static value({@today})')
                .setDefinition(Opportunity.CloseDate, 'function-add field($days)')
                .setDefinition(Opportunity.StageName, 'random type(list) value(Prospecting,Qualification, Needs Analysis)')
                .setDefinition(Opportunity.Amount, 'random type(number) from(1000) to(10000) scale(2)')
            );
    }

    public static Forceea.Template templateB2bOpportunitiesWithRelated() {
        return new Forceea.Template()
            .add(templateMajorAccounts())
            .add(B2B_OPPORTUNITIES, templateOpportunities().getFObject(OPPORTUNITIES)
                .setVariable('recordType', 'B2BOpportunity')
                .setDefinition(Opportunity.RecordTypeId, 'static value({@recordType})')
                .setDefinition(Opportunity.Name, 'static value(Opportunity-)')
                .setDefinition(Opportunity.Name, 'serial type(number) from(1) step(1) scale(0)')
                .setDefinition(Opportunity.AccountId, 'serial lookup(Account) mode(cyclical) source(forceea)')
            );
    }

    public static void insertAsync() {
        Forceea.Template template = DataFactory.templateB2bOpportunitiesWithRelated();
        new FObjectAsync(template)
            .setNumberOfIterations(1000)
            .setNumberOfJobs(20)
            .insertRecords();
    }

    public static void deleteAsync() {
        Forceea.Template template = DataFactory.templateB2bOpportunitiesWithRelated();
        new FObjectAsync(template)
            .deleteRecords();
    }

}
```

**Comment by Pooja-sfdc** [comment]
Hi @nmitrakis , 

Thanks for above clarification!

I tried accessing the Forceea user guide, which I was trying to access through below link:
https://nmitrakis.com/Forceea131-user-guide

But I'm unable to access the same. 

Could you please send me the link to access the guide which i can access easily?

Thanks & Regards,
Pooja Agrawal

**Comment by nmitrakis** [comment]
@Pooja-sfdc you've been using a very very old version. Now we are on v2.6!
You can find the latest Success Guide at https://rebrand.ly/cgh14.

**Comment by Pooja-sfdc** [comment]
Thanks @nmitrakis ! I will close the issue.

Kind Regards,
Pooja
