### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by nmitrakis** [Forceea/Forceea-data-factory#205]
### What is the current situation?
Forceea doesn't provide an easy way to bring existing lists into field definitions. One could write a method to convert a list
to a comma separated string and insert the string into the definition as a variable, e.g.
```
.setVariable('myList', getMyList())
.setDefinition(Account.MyField__c, 'serial type(list) value({@myList});
```
This approach will add more workload, because Forceea will parse the list string, so it's not considered effecient.

### Proposed solution
- The new method `setList(String listName, List<...> values)` will define a list of various data types (overloaded method)
- The user will use `{!listName}` to insert the list into a value parameter

### Benefits of new functionality
Forceea will replace the list values on run-time and efficiently create the required values.
A description of the benefits of the proposed solution.

**Comment by wrt83** [comment]
@nmitrakis , It looks like this is exactly what I might need.  Should I assume this is in the next release?

I have a scenario where I need to define a list of blobs  (or string where forceea does the conversion) and cannot find a way to make this work when the content is json

e.g.  .setDefinition(ContentVersion.VersionData, 'serial type(list) value({"key1": "val1", "key2": "val2") mode(cyclical)')

**Comment by nmitrakis** [comment]
@wrt83 Forceea  does not support population of JSON properties getting the key/value pairs from a random list. It seems an interesting feature to be implemented though.

**Comment by wrt83** [comment]
@nmitrakis, Thanks for the quick response!   That does sound like a neat feature, but wasn't exactly what I was hoping to achieve. 

My issue is around the processing of list.  E.g.  If I wanted to use the below text in a definition, I don't see a way to do so given the way Forceea processes strings to lists of strings and the limits on escape characters.  If there were a way to provide a list<strings> that doesn't get processed, I think that would solve the issue. 

E.g. it appears we can't use this text:  The "big eared rabbit" jumped the fence, narrowly avoiding a fox.

setDefinition(Account.Description, 'static value(The "big eared rabbit" jumped the fence, narrowly avoiding a fox.)'

**Comment by nmitrakis** [comment]
I see what you mean. You can use 
```
.setDefinition(Account.Name, 'static value(The \"big eared rabbit\" jumped the fence narrowly avoiding a fox.)');
```
which works fine, but it doesn't have the comma. Normally it should accept the , in a static value command, but it seems there is a bug that wasn't tracked so far. Bypassing this issue, the final solution is:
```
FObject.setGlobalVerbose('debug');
FObject obj = new FObject(Account.SObjectType, 1)
    .setDefinition(Account.Name, 'static value(The \"big eared rabbit\" jumped the fence)')
    .setDefinition(Account.Name, 'static value(", narrowly avoiding a fox.")');
obj.getRecords();
```
